### ISSUE TITLE
Code Louisville Front End Courses to be completed

### ISSUE THREAD

**Issue by Tim-Fili** [Tim-Fili/treehouse1#3]
# TODO
*Courses left to complete the Code Louisville Front End Dev Courses Track*

* [ ] Git Hub Basics
* [x] Enhance Design with CSS
* [x] Debugging CSS with Chrome DevTools
* [ ] Mobile-First CSS Layout
* [ ] Responsive Layouts
* [x] Practice Media Queries
* [ ] CSS Flexbox Layout
* [ ] HTML Forms
* [ ] JavaScript Numbers
* [ ] JavaScript Functions
* [ ] JavaScript Loops
* [ ] JavaScript Arrays
* [ ] JavaScript Objects
* [ ] CSS Selectors
* [ ] Accessibility For Web Developers
* [ ] Website Optimization

🌮 🌮 🌮
